# Generated by Django 5.0 on 2026-01-25 09:05

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Projeto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=200)),
                ("descricao", models.TextField()),
                (
                    "categoria",
                    models.CharField(
                        choices=[
                            ("uiux", "UI/UX"),
                            ("web", "Web"),
                            ("mobile", "Mobile"),
                        ],
                        max_length=20,
                    ),
                ),
                ("imagem", models.ImageField(upload_to="projects/")),
                ("link", models.URLField()),
                ("ordem", models.IntegerField(default=0)),
            ],
            options={
                "verbose_name": "Projeto",
                "verbose_name_plural": "Projetos",
                "ordering": ["ordem"],
            },
        ),
        migrations.CreateModel(
            name="SobreMim",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=200)),
                ("titulo", models.CharField(max_length=200)),
                ("descricao", models.TextField()),
                (
                    "foto",
                    models.ImageField(blank=True, null=True, upload_to="profile/"),
                ),
                (
                    "curriculo",
                    models.FileField(blank=True, null=True, upload_to="documents/"),
                ),
            ],
            options={
                "verbose_name": "Sobre Mim",
                "verbose_name_plural": "Sobre Mim",
            },
        ),
    ]
