# Generated by Django 5.0 on 2026-01-25 09:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AboutMe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(default="About me", max_length=200)),
                ("descricao", models.TextField()),
            ],
            options={
                "verbose_name": "Sobre Mim",
                "verbose_name_plural": "Sobre Mim",
            },
        ),
        migrations.CreateModel(
            name="Curriculo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("arquivo", models.FileField(upload_to="curriculo/")),
                ("nome_botao", models.CharField(default="Curriculum", max_length=100)),
            ],
            options={
                "verbose_name": "Currículo",
                "verbose_name_plural": "Currículo",
            },
        ),
        migrations.CreateModel(
            name="Hero",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=200)),
                ("titulo", models.CharField(max_length=200)),
                ("descricao", models.TextField()),
                (
                    "foto",
                    models.ImageField(blank=True, null=True, upload_to="profile/"),
                ),
            ],
            options={
                "verbose_name": "Hero",
                "verbose_name_plural": "Hero",
            },
        ),
        migrations.DeleteModel(
            name="SobreMim",
        ),
    ]
