# Generated by Django 5.0 on 2026-01-25 09:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0002_aboutme_curriculo_hero_delete_sobremim"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contato",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(default="Let's talk", max_length=200)),
                (
                    "subtitulo",
                    models.CharField(
                        default="Questions or remarks? Just write us a message!",
                        max_length=300,
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
            ],
            options={
                "verbose_name": "Configuração de Contato",
                "verbose_name_plural": "Configuração de Contato",
            },
        ),
        migrations.CreateModel(
            name="Servico",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        help_text="Nome do ícone Bootstrap Icons (ex: laptop-fill)",
                        max_length=100,
                    ),
                ),
                ("titulo", models.CharField(max_length=200)),
                ("descricao", models.TextField()),
            ],
            options={
                "verbose_name": "Serviço",
                "verbose_name_plural": "Serviços",
            },
        ),
        migrations.AddField(
            model_name="aboutme",
            name="foto",
            field=models.ImageField(blank=True, null=True, upload_to="profile/"),
        ),
    ]
