# Generated by Django 5.0 on 2026-01-25 09:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0003_contato_servico_aboutme_foto"),
    ]

    operations = [
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=200)),
                (
                    "percentual",
                    models.IntegerField(default=50, help_text="Porcentagem de 0 a 100"),
                ),
                ("ordem", models.IntegerField(default=0)),
            ],
            options={
                "verbose_name": "Skill",
                "verbose_name_plural": "Skills",
                "ordering": ["ordem"],
            },
        ),
    ]
