# Generated by Django 5.0 on 2026-01-25 09:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0004_skill"),
    ]

    operations = [
        migrations.AddField(
            model_name="hero",
            name="titulo_final",
            field=models.CharField(
                blank=True,
                help_text="Texto final do título (alinhado à direita)",
                max_length=200,
            ),
        ),
    ]
