# Generated by Django 5.0 on 2026-01-25 09:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0005_hero_titulo_final"),
    ]

    operations = [
        migrations.AddField(
            model_name="hero",
            name="titulo_2",
            field=models.CharField(
                blank=True, help_text="Segunda parte do título", max_length=200
            ),
        ),
    ]
