# Generated by Django 5.0 on 2026-01-25 09:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0006_hero_titulo_2"),
    ]

    operations = [
        migrations.AddField(
            model_name="aboutme",
            name="titulo_destaque",
            field=models.CharField(
                blank=True,
                default="me",
                help_text="Última palavra que aparecerá colorida",
                max_length=100,
            ),
        ),
    ]
