# Generated by Django 5.0 on 2026-01-28 05:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0007_aboutme_titulo_destaque"),
    ]

    operations = [
        migrations.AlterField(
            model_name="servico",
            name="icon",
            field=models.ImageField(
                blank=True,
                help_text="Imagem do ícone (opcional)",
                null=True,
                upload_to="services/icons/",
            ),
        ),
    ]
